name: Publish And Deploy # 自动化部署的名称
on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境
    steps:

    # 部署到服务器
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_SERVER_HOST }} # 机器的host地址
        username: ${{ secrets.DEPLOY_SERVER_USERNAME }} # 登录host的用户名
        password: ${{ secrets.DEPLOY_SERVER_PWD }} # 登录host的密码
        port: ${{ secrets.DEPLOY_SERVER_PORT }}  # 登录host的端口号
        script: | # 执行命令构建 （在远程服务器中）
          cd /root
          ./pull.sh
          pwd
          exit



          
      
